"""remove last_name from attendence Table

Revision ID: 3810372869f4
Revises: a42ea672b233
Create Date: 2025-07-25 20:21:19.494495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3810372869f4'
down_revision: Union[str, Sequence[str], None] = 'a42ea672b233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
