"""add otp_created_at to users

Revision ID: 722eb2f10c54
Revises: 1b993c29012d
Create Date: 2025-07-28 18:25:17.423720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722eb2f10c54'
down_revision: Union[str, Sequence[str], None] = '1b993c29012d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_created_at')
    # ### end Alembic commands ###
